# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flNs-oRbWInbYapk3MDzGJn4cy2D2g34
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler, LabelEncoder
df = pd.read_csv('anomaly_train.csv')
df.fillna(0, inplace=True)

# (EDA)
print("Briefing the Statistics:")
print(df.describe())
sns.pairplot(df)
plt.show()

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

le = LabelEncoder()
for c in categorical_columns:
    df[c] = le.fit_transform(df[c])
X = df.drop(['Time'], axis=1)
scaler = StandardScaler()
X_scale = scaler.fit_transform(X)
outl_detec = IsolationForest(contamination=0.05, random_state=44)
outliers = outl_detec.fit_predict(X_scale)
df['anomaly_flag'] = np.where(outliers == -1, 'Anomaly', 'Normal')

print("Flagged-Anomalies are:")
print(df[df['anomaly_flag'] == 'Anomaly'])