# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNy8LgZQe1ymS9hTbb932j_0kTUM9eMP
"""

#10
import pandas as pd
import numpy as np
data={'Department':['electronics','electronics','clothing','clothing','homegoods'],'salesperson':['alice','bob','charlie','david','eve'],'sales':[7000,5000,4000,3000,6000]}
df=pd.DataFrame(data,index=['0','1','2','3','4'])
print(df)
for i in range(5):
  if(df['Department'][i]=='electronics'):
   e=np.array(df['salesperson'][i])
   se=np.array(df['sales'][i])
  elif(df['Department'][i]=='clothing'):
   c=np.array(df['salesperson'][i])
   sc=np.array(df['sales'][i])
  elif(df['Department'][i]=='homegoods'):
   h=np.array(df['salesperson'][i])
   sh=np.array(df['sales'][i])
average_electronics=sum(se)/len(e)
average_clothing=sum(sc)/len(c)
average_homegoods=sum(sh)/len(h)
averages=np.array(average_electronics,average_clothing,average_homegoods)
print(averages)

#9
employee_data={'employee':['alice','bob','charlie','david','eve'],'department':['hr','it','finance','it'],'manager':['john','rachel','emily','rachel']}
project_data={'employee':['alice','charlie','eve'],'project':['p1','p3','p2']}
df=pd.DataFrame(employee_data,index=['0','1','2','3','4'])
d=pd.DataFrame(project_data,index=['0','1','2'])
for i in range(5):
  for j in range(3):
    if(df['employee'][i]==d['employee'][j]):
      a={df['department'][i]:d['project'][j],df['manager'][i]}
    else:
      a={df['department'][i]:'not given',df['manager'][i]}
print(a)

#8
import pandas as pd
import numpy as np
supermarket={'product':['apple','bananas','cherries','dates','eldberries','flour','grapes'],'category':['fruit','fruit','fruit','fruit','fruit','bakery','fruit'],'price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],'promotion':['true','false','true','true','false','true','false']}
df=pd.DataFrame(supermarket,index=['0','1','2','3','4','5','6'])
avg=sum(df['price'])/7
for i in range(7):
  if(df['category'][i]=='fruit' and df['promotion'][i]=='false' and df['price'][i]>avg):
    arr=np.array(df['product'][i])
print(arr)

#7
#missing data but writing logic
for i in range(7):
  if(df['age'][i]<45 and df['department'][i]=='hr')
   lis=[df['name'][i],df['city'][i]]
print(lis)

#5
scores=np.array([])